import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Post from "../components/CreatePost";
import Sidebar from "../components/sidebar";
import Aside from "../components/aside";
import Context from "../components/Context";
import Feed from "../components/Feed";
import { doc } from "firebase/firestore";
import { useEffect } from "react";
import Login from "../components/Login";

export default function Home() {
  const User = null;
  return (
    <div className={styles.container}>
      <Head>
        <title>Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/peer.png" />
      </Head>
      <div className="w-full  bg-gray-100">
        <Header />

        <div className="xl:max-w-screen h-fit flex mx-auto justify-center mt-0 lg:pl-48">
          <Sidebar />
          <div className="w-full md:w-5/6  border-gray-200 border-r">
            <div className="bg-white w-full border-l flex relative">
              <div className="lg:w-[680px] border-r w-full outline-none mb-32 border-gray-200 relative mt-8 lg:mb-16 bg-white">
                <Nav />
                <Post />
                <Feed />
              </div>
              <div className="fixed -right-1 bg-gray-100">
                <Aside />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
