import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Post from "../components/CreatePost";
import Sidebar from "../components/sidebar";
import Aside from "../components/aside";
import Context from "../components/Context";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create a post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full  bg-gray-100">
        <Header />

        <div className="xl:max-w-screen h-screen flex mx-auto  overflow-hidden justify-center mt-0 pl-48">
          <Sidebar />
          <div className="w-full md:w-5/6 border-gray-200 overflow-y-scroll border-l border-r">
            <div className="bg-white w-full flex relative">
              <div className="lg:w-[680px] mb-32 border-gray-200 relative mt-8 lg:mb-16 bg-white">
                <Nav />
                <Post />
                <Feed />
              </div>
              <div className="fixed -right-1">
                <Aside />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
