import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Post from "../components/CreatePost";
import Sidebar from "../components/sidebar";
import Aside from "../components/aside";
import Context from "../components/Context";
import Feed from "../components/Feed";
import { doc } from "firebase/firestore";
import { useEffect } from "react";
import Login from "../components/Login";

export default function Home() {
  const User = null;
  return (
    <div className={styles.container}>
      <Head>
        <title>Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABKVBMVEUAq0X///8kKS0ArEkgKy4Dq0IPQCv///0iKTAAqUcYlE8BqUIfJCnu8PA+Q0UBrEBDR0oeLCoZo1EOKyEmKC2io6UPKx4jKSwMViwNFxu+v8AGEBYFp0ciKTEjKyonJzGIio0WGiAuMjYPpUzP0dMfLC0qJiwnKSoVe0UXLSopJjEdLC8TMyUNqE0kIykdKiULQyMSLRcAAAApJTYUbzcQKSUTNyYYZjsTgUQXVDIoKSQQQygYbTwOYC8Sm0wsJiceKyADQRwejk0dbUIRIycZTDUfJzRpbXJQVVoZGiPh4d9MUU4UHxcjbUyTlZivsLAwIS0dHBoMZCtucXQfnF4RdzoAZSMXplwmgVEHFyBbY2V8fX4DHxsQjkS4ubsCUiMLOS8lh1ADLgwwzl0+AAAOkklEQVR4nO2dDVvaShbHQzLBhAQxODqoeRFDiCRg8FoVClIv7bWWu2vtdru927t2X77/h9gzw4tW0JpqSfCZf59a2hoffpyZc87MnJkRBC4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLq7nJVVVk34LXI+XFkdJv9kfkhxHSb/ZHxInXGxCcKWqJLBfoz/ufyEtmu+lgKoZR+yJpN92DJkuqBhHbqMBmNLtHzT1DwmKmQA6VEFWNfPF6urq4epY699TvX7ULB13W1c9twGBgwUP2jcls2Gq6Qok0KHo5y51a56NjDjyvNpqPdtsH7dyxQb8ENWU4bcqpcgFgfEE5jCkhiR1CX7pkzg6sywFIWQbR53Sbs414QeCLeVCoZA02ESFAv3QzQZ0KMns7r16aeM4UkRFJAQRoqBovXnSgvaqUj5ZS01XlARZkzWNulBZ6+5Vfe8hXI7jYEy/vHr1yvdt2zZCC1f90/3mca5oAqGWHg9rmmBG+qEXhILQRaKNiKiLTIp4l8iE1fd9YhNop/QvxDbs6Nduv9gQtNS4U6lhQqOSJWilRbf4OkS2Qoi98UCVy2/eIKRYluVUq1USgmrr9c5xn3mdlEgD/64WW93X3dfH3d/OLL/q2zsXaw/Sxfb22/Nl/O7dnrNHCLU6GBM+oNXObq+RNNhEYEC12G8e6kYY7XsHio19fSWfebiWBpsXv//lL290JIoYLOlYjuXtn1ylBrEgSZqQyyIMNiAipobQl+MQDjEr2yv6hq6LGFNMP6pn/9pTIfSzLDdhQojOMhBeu5EfIQTlKxfLG0QkCCiJAXnASc4VCppppoFQewpCCrm2ousohL6IPM+ot1tuoQAJzjMhXKLK5N+vgHMFRIgdltH51JC16bR8oQlB78UNIBTxnuOQ7G5RSjx/e1JChpjfLgOijqtYQauvPwuFhLPwJ7chaHOlDEn5Kzs8s+rd3nPphzdQM5nB2w8E+QRZjp3t5hJG/AmE1JQXGzaCdmrbp9nXCcf+JyccafMDy8Vh5FjbLWoajLGTGhX/LMJMZU+nhJ5t/Np3ZYj8wnMjzFSWdZFOA0Doz6nycyTMbEKiSxGVwxNXUM1k+H4qYaaiE5rNH4hZSG6EpCbffh4huNT3ZUjD8YEVNa8EOamg8RMJIWxsl2mCaimrJ0U1qQT15xJmzt9h7CkOyrbc1BNubn7dvKVKZXAvIXwZ7OzhSHSsqNQTEmqmDybc2ZpWWd/5sjagXe5GVvoNIXRF36CzB/Vdt8AmnwV5zivHDyZc0cVp6bpeFs+/0u+femY00nj7wRNFJFIjUkKVLqMvECFR4LdePl/LL2Vm25CFDBEh42i3QRdtoDfOOfI/jnDEqZdXKlMPjJvtdpmIKNRfghEFutYlzHnl+CkIRdHXty5uPzQmzL/TCQqdy6OWKUhAqC0kIfTI8hfmWJemCDPbOtgwuIyOi3TeDXrhYhKC01kezCasYN/2nMDL9lzqZ+a9ZvM0hApdxdFXBjMJMx8/RMixwsNW0ZTpOlfqCcE3Yjz6OgZkiOUv+ZmElQ+RrYQh+VvPlAtCmm1IfNFysG0gfFkVPYKDg4PJU2ytbePjjAczS/nf2adD6n+nc4vqnJObWITVahBg4iGL4GoVo1BxviXE+toswsxFmX4HOWyZQDjvgWIsQgNZFvKMUKkZSLEUatRvCPWZjy5B1KffIUZdl7bSNBPWkOMQGwcBMcLwLKj60S0b4vL2DMKlPO3EWLRLPU2e+/J3PBviS1w7jXxi+9gJzhTDuN1K8db0s+ByPurMLzWvVLqOkd68FAjxf9rHx6VS8yjaqyoo9G7bcJYRgXBti36Hkm2Z2twT01jRAlXt9t+LxeLnXKvbrkcEoSnCGQ9D1KhQQtGqf3JTTogvX5aKkqZJjYbba5WOjGlC8cPmDBvmh4SnL1wh1YQE4dOTBq1N0bRCQe3tdg7RkO4GYfliBmGGRQsr+huby0gvoWg7qNQQTBUIYYBgFnv/2PedULm8FMPJ4/rb8drFTZ3TeIGids+EwdN8J2xiEpKSKzSAUAZDqG6xd7yuWCGu4huEK/kZhB9HhDkVPpr05jTXhPRJyWy4bq50KoaGiK+f13cGMwi3aVajGM2cuSCEMh2sm6ppurm2HdY8bN94vDKDcG1jTAjGn2/e9qOEo4pwrdE6IiHyr9M3pTyL8D0ltBihsECEtJZULh5HWMExCLUFIRwN88yC1N8XLQVfP75xZyu1FqiVjh6WNXAcYETHIt/phxc3++EieJpRybpGp87M3bpj3e9Ll4a+FC0IoXptQzqFrZn9rIiuW6l+zp6+xUjjoRKKpSLtvekdW8wmVHMdG02mbMTyR5Zr3yJcYYSYEaZ49DSLUC7In3/zvAkhKa+x2ahbhHRqXwntE8jbF4tQkORC4XPb8PwJ4V6F0X1LOGCORom67vx3mjySUC1QwuiaENLSpel+uLnFCNd33flvyny8DeVeZ2xDaIoba5kZNmSTbQo66tPdQ3NeC35kPwRCIdchHgOk44dyfhYhG1ooXjOnavK8p4Qfa0MaLY5wOI74k/HvN4SDZUpIYHhIP5E5Vw3HGuPTEbALY4obNhQ0t7W+h8ikFzK8W4SbZdqAxei4SKcw5lz5HYswDOxSke7CG++tBEcjfS5Fl9WREcnUJA3j3X5X9W1C9vsNar85u9N4KzOXL9ufpWHKBi6GzmS4n//Y96ukRgnJ1qxJ/cxSfmVvDxORQDc0VeiH6Z2nIYYftT83GnTf6FBubrd0FBHiGbS+S5+5MJPJfC0rGFexR+O9SrOEFBOS6Lc/Wp92R3rRPWkeRbbnGSxrK5/fUWl0ruuKE4i1llmgwUKdb217rFbqVQOjfrR/GtWoDA8hsB1GIZ2LErfuAqxUfQ8FgZGl9SZ0aiDFNgzpnibDxo7C5DiBRfetOXsY8tHtu2rF3u75dujg+rELKd78S2njzQhbZ2fI85A12gVs20qIrOAyIG923t/Blxn8s+oboeV1+nQjIN1Dk+JW6leDgyp4RQvTfaO27fuEwJN7e/qXuyvc/nxTfRV5Vg1GTrSUxlTTbMPIIBgim00cx2HtE/qfb/zrX19mhcGRKmWLEiqruw1JHRKmz4ZLI0KFjg8wVkYCD6nr5V92tqfrodhTw7q2FT3AUU3U28WENs/EIbzeGjxcDcU75x8vZuONn4JRBQ5QzbCPdhsJbYB6MGFlWoPBd0ttKzu6WA1DdHrcS+qUhQcT3mOnu/8zfw4DQz+0lM6VlFShd7wq6KXb+o4JP25AwwbHFHUhnZGSKYOORTgF+B3Ciw0CI3vDjjo5uZD6Ou8fIHxfpjNsqBZ1WnQzaTKAj63Vvw/1K524URQUHr1ge2bSvitoNsY9hJvgRuk8sFJrQxs1TSnF0SKWxrRff/GdAwdD5vrvvguDinmXBv88wmEEyV+UfYSUIBAPs/2iOfctCD+VkAH+qdNUxgsOvGar2JDAhM9rV1AFAj0+UAzPQtld16TTxpqpLkI8fKDWdJrDOoGj1Dq7PTpmokf8PB8bggFZSTAMJlGnBRak048Jnur21ISDbaKzo2pE265BE6UVUCO+BfelwxAxWFve0FmcV5Sw3m4V4YcPVyqSO2TxKW04+NP/QMtOaCW/YoWdfoMelKYxsgUgnM5Jh6nMOJvJf/3yS5nOdCDn4NKP0NmvrZ4pCIkfbfIYG17j5Strb5eH/kXEDkYhIkb9U8+lbTRxxEe20nwe6D6u7JT18YaTg8Cu0bnDFxQQAr2ZUBiMT3ixPa0/357vbG2Vyzq5rhg6UGwbe9lPRRro6cl0C0O4vFGelj4x3Vh0Przqd1pscjQNgHHm2sj1UXvX3zzW5F98bNWafVrtzAJ9wnjxCMUZmiaMotV2zmT1YMNAv0A2fBAhqR2d5CQa+6RRKpq0GWMRTo4tnbTU8YuRpyHE+88f9DgaQS7Qc18l4Ez6MNp4a09oCCg6FjUbvBge9qmEoW0rzhmqHbV7jaHRUnMKbay1pyGeyGb3MT0ksWqNDoP0CQ4CvN6GwVJiw6Q79GO7ZG2bDBEVIPSIbduOYtQ73ZybvhO+4+0KmgQKQg/XAfNVfdvzQsVx0Grz5KrYUGkpQtI971vF6oc3HYxioRC6n+/Da4TC5nG/qEIATPyYxCnFJWT2g7GREwSB4zihFVy+OqXnQBddVU7BKYnTikkoUodKpdBe6OMzy6g3u1euaZqaTMubF5uQ2Q/oPOQZRnS6Xt/Pdtrd/nAQIYwGukkDTSmuL/VqtcPDw9X1o2yndLzbosZjB57LtBTIpEXRSRPdVqxWKp5ZndZVq3UF6hWLrusm/fYfoHjR4kxp91yG5rqsuC3pt/8AxSHE2EHtHr34gF6CobLy0vQrXsWQ5ZXoyI+tky3KHSzxqqCVWsll1etM2px3v/yY4hEiINTYMUEUcDHue4o3tnj2hNgKKaGwUDchxSKsOkDI7jV5FoS3akpWdAV8qQG+dN7FhY9UDBuOCc1nQDjIT2tFFJ8LIWhnhshzIiQ6HQteL0XA6+Ffng3hneKEqdSdhDeWIiYvny0hXZ1gXdFXDLYbe6EI5eE9M55NphivGydGCq6t1pBu7Jd66uKkM0xgQw1s6BGR3CWxGoTeYbvbff26++LKFWRpEYb2E40J8T0X5AUBqu3/l81dNKCJSqa7CGP7sUaEBN/dSBXnQKnt902NXokHWbdkpujOse9LHhFW77kqjzjY3m+5Gq2sMLUFmZ6ZqGCOWuk9MjD29//rqgLdPUov9VwsXzokNOy7u6Ed+aK332/QBV12n+fiEcq5juHdc9lojRBjP6eym5tkYe5Hyj1SLB72mqv3af3wcPV/V6ZGz6GTF+6CeWYOevLafZf+shnueZ+68qT6zlXO6qLd3DxD917HLS0+H9NzukB9tjjh4ku7W0m/NS4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4urifX/wEbkiegVhxD+QAAAABJRU5ErkJggg==" />
      </Head>
      <div className="w-full  bg-gray-100">
        <Header />

        <div className="xl:max-w-screen h-fit flex mx-auto justify-center mt-0 lg:pl-48">
          <Sidebar />
          <div className="w-full md:w-5/6  border-gray-200 border-r">
            <div className="bg-white w-full border-l flex relative">
              <div className="lg:w-[680px] border-r w-full outline-none mb-32 border-gray-200 relative mt-8 lg:mb-16 bg-white">
                <Nav />
                <Post />
                <Feed />
              </div>
              <div className="fixed -right-1 bg-gray-100">
                <Aside />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
